### ISSUE TITLE
REQUEST - Docker compose instructions

### ISSUE THREAD

**Issue by alexanderjacuna** [daswer123/xtts-finetune-webui#93]
This is a request for some instructions / supported compose yaml file to use xtts-finetune-webui with docker compose. Using an internet tool I was able to convert the docker run command into the below compose example but it doesn't work, results in a broken website that partially loads. Since there is no official docker compose file, that I could find, I thought a request as the best way forward rather then opening a bug.

```YAML
version: "3.3"
services:
  fine-tune-xtts:
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    pull_policy: always
    ports:
      - 7860:7860
    platform: linux/amd64
    image: athomasson2/fine_tune_xtts:huggingface
    command: python app.py
    container_name: fine-tune-xtts
networks: {}
```
